config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index"
  resources :menu_items
  resources :menus
  resources :users

  # auth
  get "/login" => "home#login", as: :login_path
  post "/login" => "users#login"

  delete "/logout" => "users#logout", as: :logout

  get "/signup" => "home#signup"
  post "/signup" => "users#create", as: :signup_path

  # cart
  get "/checkout" => "carts#index"
  resources :carts

  # order
  get "/orders/pending" => "orders#pending"
  resources :orders

  # dashboard
  get "/dashboard" => "home#dashboard"

  #sales
  get "/sales" => "sales#index"
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu

  validates :menu_id, presence: true
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :description, presence: true
  validates :description, length: { minimum: 3 }
  validates :image, presence: true
  validates :image, length: { minimum: 3 }
  validates :price, presence: true
  validates :prep_time, presence: true
  validates :prep_time, numericality: { greater_than: 0 }
  validates :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :is_veg, inclusion: { in: [true, false] }

  def self.of_menu(id)
    all.where(menu_id: id)
  end

  def self.get_active
    MenuItem.of_menu(Menu.get_active.id)
  end

  def to_string
    "#{id}| #{menu_id} | #{name} | #{description} | #{price}"
  end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  skip_before_action :ensure_user_logged_in, only: [:index, :show]
  before_action except: [:show] do
    limit_access_to(["admin"])
  end

  def index
    menu_items = MenuItem.all
    render "menu_item/index", :locals => { menu_items: menu_items }
  end

  def new
    render "menu_item/new"
  end

  def edit
    menu_item = MenuItem.find(params[:id])
    render :template => "menu_item/edit", :locals => { menu_item: menu_item }
  end

  def show
    menu_item = MenuItem.find(params[:id])
    render :template => "menu_item/show", :locals => { menu_item: menu_item }
  end

  def create
    new_menu_item = MenuItem.new({
      menu_id: params[:menu_id],
      name: params[:name],
      description: params[:description],
      image: params[:image],
      is_veg: params[:is_veg],
      prep_time: params[:prep_time],
      price: params[:price],
    })
    if new_menu_item.save
      redirect_to menu_item_url(new_menu_item)
    else
      error = new_menu_item.errors.full_messages
      flash[:error] = error[0...3]
      redirect_to new_menu_item_path
    end
  end

  def update
    id = params[:id]
    name = params[:name]
    description = params[:description]
    price = params[:price]
    new_menu_item = MenuItem.find(id)

    new_menu_item.name = name if name
    new_menu_item.description = description if description
    new_menu_item.price = price if price

    if new_menu_item.save
      flash[:success] = ["Menu item Updated successfully"]
      redirect_to menu_item_path(new_menu_item.id)
    else
      error = new_menu_item.errors.full_messages
      flash[:error] = error[0...3]
      redirect_to edit_menu_item_path(new_menu_item.id)
    end
  end

  def destroy
    id = params[:id]
    menu_item = MenuItem.find(id)
    menu_item.destroy
    render plain: ["DELETED MENU_ITEM WITH ID #{id}"]
  end
end

app/helpers/menu_item_helper.rb
module MenuItemHelper
end

app/views/menu_item/_menu_item_row.html.erb
<tr class="bg-white sm:hover:bg-green-50 flex sm:table-row flex-row sm:flex-row flex-wrap sm:flex-no-wrap mb-10 sm:mb-0">
      <td class="w-full sm:w-auto p-3 text-green-800 text-center border border-b block sm:table-cell relative sm:static underline">
        <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Item Id</span>
        <a href= <%= menu_item_path(item.id) %> > # <%= item.id %> </a>
      </td>
      <% if show_menu_id %>
      <td class="w-full sm:w-auto p-3 text-green-800 text-center border border-b block sm:table-cell relative sm:static underline">
        <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Menu Id</span>
        <a href=<%= menu_path(item.menu_id) %>> # <%= item.menu_id %> </a>
      </td>  
      <% end %>
      
      <td class="w-full sm:w-auto p-3 text-green-800 text-center border border-b block sm:table-cell relative sm:static">
        <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Name</span>
        <%= item.name %>
      </td>
      <td class="w-full sm:w-auto p-3 text-center border border-b block sm:table-cell relative sm:static">
        <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Price</span>
        <%= item.price %>
      </td>
      <td class="w-full sm:w-auto p-3 text-green-900 text-center border border-b block sm:table-cell relative sm:static">
        <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Actions</span>
        <a href=<%= edit_menu_item_path(item.id) %> class="px-3 py-1 rounded text-blue-900 bg-blue-200">Edit</a>
        <%= link_to "Delete", menu_item_path(item.id), method: "delete", class: "px-3 py-1 rounded text-red-900 bg-red-200" %>

      </td>
</tr>

app/views/menu_item/edit.html.erb
<div class="max-w-screen-sm mx-auto">
  <div class="p-6 w-full">
    <h1 class="text-3xl py-3 border-b border-green-900 mb-4 pb-4 border-opacity-20">Update Menu Item</h1>
    <%= form_with url: menu_item_path, method: "patch" do |form| %> 
    <div class="px-3 mb-5">
      <label for="menu">Menu</label>
      <div class="ml-9 w-10 z-10 pl-1 text-center flex items-center justify-center mt-1">
        <select name="menu_item_id" id="menu" class="py-2 px-4 border-2 rounded-lg">
        <%= options_for_select(Menu.options, :selected => menu_item.menu_id) %>
        </select>
      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :name, "Name" %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.text_field :name, :value => menu_item.name, class: "w-full -ml-10 pl-6 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>

      </div>
    </div>
    <div class="px-3 mb-5">
    <%= form.label :description, "Description" %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.text_area :description, :value => menu_item.description, rows: "3", class: "w-full -ml-10 pl-3 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>

      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :price, "Price" %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.number_field :price, step: 1, min: 1, :value => menu_item.price, class: "w-full -ml-10 pl-4 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>
        
      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :image, "Images Url" %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.text_field :image, :value => menu_item.image, class: "w-full -ml-10 pl-6 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>   
      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :prep_time, "Preparation Time ( Min )" %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.number_field :prep_time, :value => menu_item.prep_time, min: 1, :require => true, class: "w-full -ml-10 pl-4 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>
      </div>
    </div>
    <div class="px-3 mb-5">
       <label class="inline-flex items-center">
        <%= form.radio_button :is_veg, true, :checked => menu_item.is_veg %>
        <span class="ml-2 text-green-600">Veg</span>
      </label>
      <label class="inline-flex items-center ml-6">
        <%= form.radio_button :is_veg, false, :checked => !menu_item.is_veg %>
        <span class="ml-2 text-red-600">Non Veg</span>
      </label>
    </div>
    <div class="flex">
      <div class="w-full px-3 mb-5">
        <input type="submit" class="text-center block w-full mx-auto bg-green-500 hover:bg-green-700 focus:bg-green-700 text-white rounded-lg px-3 py-3 font-semibold" value="Update" />
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/menu_item/index.html.erb
<div class="max-w-screen-lg mx-auto min-h-screen pt-12" >
  <h1 class="text-3xl font-medium mb-4">Menu Items</h1>
  <a href=<%= new_menu_item_path %>  class="inline text-lg py-1 bg-blue-200 px-4 rounded-lg">Create</a>
  <table class="border-collapse w-full mt-8">
  <thead>
    <tr>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Item Id</th>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Menu Id</th>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Name</th>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Price</th>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% menu_items.each do |item| %>
    <%= render partial: "menu_item/menu_item_row", locals: { item: item, show_menu_id: true } %>
  <% end %>
    
  </tbody>
  </table>
</div>

app/views/menu_item/new.html.erb
<div class="max-w-screen-sm mx-auto">
  <div class="p-6 w-full">
    <h1 class="text-3xl py-3 border-b border-green-900 mb-4 pb-4 border-opacity-20">Create Menu Item</h1>
    <%= form_with url: menu_items_path, method: "post" do |form| %>
    <div class="px-3 mb-5">
        <%= form.label :menu %>
      <div class="ml-9 w-10 z-10 pl-1 text-center flex items-center justify-center mt-1">
        <select name="menu_id" id="menu" class="py-2 px-4 border-2 rounded-lg">
         
          <%= options_for_select(Menu.options) %>
        </select>
      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :name %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
     <%= form.text_field :name, class: "w-full -ml-10 pl-6 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600", placeholder: "Roasted Chicken" %>   
      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :description %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.text_area :description, rows: 3, class: "w-full -ml-10 pl-3 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>
      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :price %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.number_field :price, min: 1, :require => true, class: "w-full -ml-10 pl-4 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>
      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :image, "Images Url" %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.text_field :image, class: "w-full -ml-10 pl-6 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>   
      </div>
    </div>
    <div class="px-3 mb-5">
      <%= form.label :prep_time, "Preparation Time ( Min )" %>
      <div class="flex">
        <div class="w-10 z-10 pl-1 text-center pointer-events-none flex items-center justify-center"><i class="mdi mdi-account-outline text-gray-400 text-lg"></i></div>
        <%= form.number_field :prep_time, min: 1, :require => true, class: "w-full -ml-10 pl-4 pr-3 py-2 rounded-lg border-2 border-gray-200 outline-none focus:border-green-600" %>
      </div>
    </div>
    <div class="px-3 mb-5">
      <label class="inline-flex items-center">
        <%= form.radio_button :is_veg, true, :checked => true %>
        <span class="ml-2 text-green-600">Veg</span>
      </label>
      <label class="inline-flex items-center ml-6">
        <%= form.radio_button :is_veg, false %>
        <span class="ml-2 text-red-600">Non Veg</span>
      </label>
    </div>
    <div class="flex">
      <div class="w-full px-3 mb-5">
        <input type="submit" class="text-center block w-full mx-auto bg-green-500 hover:bg-green-700 focus:bg-green-700 text-white rounded-lg px-3 py-3 font-semibold" value="CREATE" />
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/menu_item/show.html.erb
<div class="max-w-screen-lg mx-auto min-h-screen" >
<div class="flex flex-wrap md:flex-nowrap p-6">
  <div class="w-full md:w-1/2 mb-4">
    <img src=<%= menu_item.image %> alt="menu item images" class="w-full h-full rounded-lg" />
  </div>
  <div class="w-full md:w-1/2 md:pl-6">
    <h1 class="text-3xl font-medium text-green-800 mb-4"><%= menu_item.name %></h1>
    <div class="flex mb-4 p-4 border-t border-b border-green-100 text-gray-700">
      <div class="flex-1 inline-flex items-center">
        <img src=<%= image_path("clock.svg") %> class="mr-2" />
        <p><span class="text-green-900 font-bold"><%= menu_item.prep_time %></span> Min</p>
      </div>
      <div class="flex-1 inline-flex items-center">
        <div class="border-2 <%= menu_item.is_veg ? "border-green-500" : "border-red-500" %> mr-2 rounded flex items-center justify-center" style="width:20px;height:20px;">
          <span class="<%= menu_item.is_veg ? "bg-green-500" : "bg-red-500" %> rounded-xl" style="width:6px;height:6px;"></span>
        </div>
        <p><%= menu_item.is_veg ? "Veg" : "Non-Veg" %> </p>
      </div>
    </div>
    <div class="mb-5">
      <p class="text-lg font-medium text-green-800 mb-1">Description</p>
      <p class="text-md text-green-900"><%= menu_item.description %></p>
    </div>
    <%= form_with url: "#{carts_path}?menu_item_id=#{menu_item.id}", method: "post" do |f| %>
    
    <%= f.label :qty, "Qty", class: "mb-2" %>
    <div class="pr-8 flex mb-5">
    <%= f.number_field :qty, step: 1, class: "p-3 mx-1 p-3 bg-green-50 border border-green-200 mt-3", :value => 1, :min => 1 %>
    </div>
    <% if @current_user %>
      
    <input type="submit" class="w-full block px-4 pt-3 pb-4 border border-green-200 bg-green-500 text-center font-medium text-white hover:bg-green-400 transition-all rounded-lg" value="ADD TO CART" />
    <% else %>
       <%= link_to "ADD TO CART", @current_user ? "#{carts_path}?menu_item_id=#{menu_item.id}" : login_url, method: @current_user ? "post" : "get", class: "block px-4 pt-3 pb-4 bg-green-500 text-center font-medium text-white hover:bg-green-400 transition-all rounded-lg" %> 
    <% end %>
    <% end %>
  </div>
</div>
</div>