config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index"
  resources :menu_items
  resources :menus
  resources :users

  # auth
  get "/login" => "home#login", as: :login_path
  post "/login" => "users#login"

  delete "/logout" => "users#logout", as: :logout

  get "/signup" => "home#signup"
  post "/signup" => "users#create", as: :signup_path

  # cart
  get "/checkout" => "carts#index"
  resources :carts

  # order
  get "/orders/pending" => "orders#pending"
  resources :orders

  # dashboard
  get "/dashboard" => "home#dashboard"

  #sales
  get "/sales" => "sales#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :ensure_user_logged_in, only: [:dashboard]

  def index
    render "Home/index", :locals => { menu_items: MenuItem.get_active }
  end

  def login
    render "users/login", :layout => "form_layout"
  end

  def signup
    render "users/signup", :layout => "form_layout"
  end

  def dashboard
    render "Home/dashboard"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/Home/_menu_item_card.html.erb
<a href=<%= menu_item_url(menu_item.id) %>>
<div class="rounded-lg overflow-hidden hover:shadow-lg transition">
  <div class="bg-cover bg-center h-56 p-4 rounded-lg" style="background-image: url(<%= menu_item.image %>)"></div>
  <div class="p-4">
    <p class="uppercase tracking-wide text-sm font-bold text-green-700"><%= menu_item.name %></p>
    <p class="text-3xl text-green-900">Rs. <%= menu_item.price %></p>
  </div>
  <div class="flex p-4 border-t border-green-100 text-gray-700">
  
    <div class="flex-1 inline-flex items-center">
      <img src=<%= image_path("clock.svg") %> class="mr-2" />
      <p><span class="text-green-900 font-bold"><%= menu_item.prep_time %></span> Min</p>
    </div>
    <div class="flex-1 inline-flex items-center">
      <div class="border-2 <%= menu_item.is_veg ? "border-green-500" : "border-red-500" %> mr-2 rounded flex items-center justify-center" style="width:20px;height:20px;">
        <span class="<%= menu_item.is_veg ? "bg-green-500" : "bg-red-500" %> rounded-xl" style="width:6px;height:6px;"></span>
      </div>
      <p><%= menu_item.is_veg ? "Veg" : "Non-Veg" %></p>
    </div>
  </div>
  <%= link_to "ADD TO CART", @current_user ? "#{carts_path}?menu_item_id=#{menu_item.id}" : login_url, method: @current_user ? "post" : "get", class: "block px-4 pt-3 pb-4 bg-green-500 text-center font-medium text-white hover:bg-green-600 transition-all rounded-lg" %> 
</div>
</a>

app/views/Home/dashboard.html.erb
<div class="max-w-screen-lg p-8 mx-auto">
  <h1 class="text-4xl font-semibold mb-8">Hi, <%= @current_user.first_name %></h1>
  <div class="flex flex-wrap">
    <div class="w-full sm:w-1/2 md:w-1/3 h-40 p-1">
      <%= link_to user_path(@current_user.id), class: "bg-green-100 w-full h-full flex items-center justify-center rounded-lg hover:bg-green-300 block" do %>
        <h1  class="text-2xl text-green-800 font-medium">Profile</h1>
      <% end %>
    </div>
    <div class="w-full sm:w-1/2 md:w-1/3 h-40 p-1">
      <a href="/orders" class="bg-green-100 w-full h-full flex items-center justify-center rounded-lg hover:bg-green-300 block">
        <h1  class="text-2xl text-green-800 font-medium">Orders</h1>
      </a>
    </div>
    <% if @current_user.role == "admin" %>
      <div class="w-full sm:w-1/2 md:w-1/3 h-40 p-1">
      <a href="/users" class="bg-green-100 w-full h-full flex items-center justify-center rounded-lg hover:bg-green-300 block">
        <h1  class="text-2xl text-green-800 font-medium">Users</h1>
      </a>
    </div>
    
    <div class="w-full sm:w-1/2 md:w-1/3 h-40 p-1">
      <a href="/menus" class="bg-green-100 w-full h-full flex items-center justify-center rounded-lg hover:bg-green-300 block">
        <h1  class="text-2xl text-green-800 font-medium">Menus</h1>
      </a>
    </div>
    <div class="w-full sm:w-1/2 md:w-1/3 h-40 p-1">
      <a href="/menu_items" class="bg-green-100 w-full h-full flex items-center justify-center rounded-lg hover:bg-green-300 block">
        <h1  class="text-2xl text-green-800 font-medium">Menus Items</h1>
      </a>
    </div>
    <div class="w-full sm:w-1/2 md:w-1/3 h-40 p-1">
      <a href="/sales" class="bg-green-100 w-full h-full flex items-center justify-center rounded-lg hover:bg-green-300 block">
        <h1 class="text-2xl text-green-800 font-medium">Sales</h1>
      </a>
    </div>
    <% end %>
    
  </div>
</div>

app/views/Home/index.html.erb
<div class="px-1 overflow-hidden max-w-screen-lg mx-auto px-8 pt-16">
  <div class="pb-6 border-b border-green-200">
    <h1 class="text-green-900 text-5xl font-semibold">Today's Menu</h1>
  </div>
  <div class="flex flex-wrap -mx-3 mt-3">
  <% menu_items.each do |menu_item| %>
  <div class="my-3 px-2 w-full overflow-hidden sm:w-full md:w-1/2 lg:w-1/3 xl:w-1/3">
    <%= render partial: "Home/menu_item_card", locals: { menu_item: menu_item } %>
  </div>
  <% end %>

</div>

</div>