config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index"
  resources :menu_items
  resources :menus
  resources :users

  # auth
  get "/login" => "home#login", as: :login_path
  post "/login" => "users#login"

  delete "/logout" => "users#logout", as: :logout

  get "/signup" => "home#signup"
  post "/signup" => "users#create", as: :signup_path

  # cart
  get "/checkout" => "carts#index"
  resources :carts

  # order
  get "/orders/pending" => "orders#pending"
  resources :orders

  # dashboard
  get "/dashboard" => "home#dashboard"

  #sales
  get "/sales" => "sales#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :menu_item

  validates :menu_item_id, presence: true
  validates :user_id, presence: true
  validates :qty, presence: true
  validates :qty, numericality: { greater_than: 0 }

  def self.of_user(id)
    all.where(user_id: id).order(:created_at)
  end

  def to_string
    "ID : #{id} | MENU ITEM : #{menu_item_id} | USER : #{user_id} | QTY : #{qty}"
  end

  def self.add_to_cart(menu_item_id, user_id, qty = 1)
    puts "#{menu_item_id}#{user_id}#{qty}"
    menu_item = of_user(user_id).where("menu_item_id = ?", menu_item_id).first
    if menu_item
      menu_item.qty = qty
      return menu_item
    else
      new_cart = Cart.new({ menu_item_id: menu_item_id, user_id: user_id, qty: qty })
      pp new_cart
      return new_cart
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    cart_items = Cart.of_user(@current_user.id)
    total = cart_items.reduce(0) { |total, cur| total + MenuItem.find(cur.menu_item_id).price * cur.qty }
    render "carts/index", :locals => { cart_items: cart_items, total: total }
  end

  def show
    id = params[:id]
    cart = Cart.find(id)
    redirect_to "#{menu_items_path}/#{cart.menu_item_id}"
  end

  def create
    menu_item_id = params[:menu_item_id]
    user_id = @current_user.id
    qty = params[:qty] ? params[:qty] : 1
    if MenuItem.exists?(menu_item_id)
      result = Cart.add_to_cart(menu_item_id, user_id, qty)

      if result.save
        flash[:success] = ["Menu Item Added To Cart"]
        redirect_to "/"
      else
        error = result.errors.full_messages
        flash[:error] = error[0...3]
        redirect_to "/"
      end
    else
      flash[:error] = ["menu item does not exits"]
      redirect_to "/"
    end
  end

  def destroy
    id = params[:id]
    user_id = @current_user.id
    cart = Cart.find_by(id: id, user_id: user_id)
    if cart
      cart.destroy
    end
    redirect_to "/checkout"
  end

  def update
    id = params[:id]
    user_id = @current_user.id
    cart = Cart.find_by(id: id, user_id: user_id)
    qty = params[:qty]
    if Integer(qty) < 1
      cart.destroy
    else
      cart.qty = qty
      if cart.save
        flash[:success] = ["Cart updated successfully"]
      else
        error = cart.errors.full_messages
        flash = error[0...3]
      end
    end
    redirect_to "/checkout"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_item_card.html.erb
<div class="px-4 py-6 bg-green-50 rounded-2xl">
  <div class="flex justify-between items-center">
    <div class="flex items-center">
      <img src=<%= menu_item.image %> width="60" class="rounded-full" style="width:56px;height:56px"/>
      <div class="flex flex-col mx-3">
        <a href=<%= menu_item_url(menu_item.id) %> class="md:text-md font-medium mb-1 text-green-800"><%= menu_item.name %></a>
        <div class="flex-1 inline-flex items-center">
          <div class="border-2 border-<%= menu_item.is_veg ? "green" : "red" %>-500 mr-2 rounded flex items-center justify-center" style="width:16px;height:16px;">
            <span class="bg-<%= menu_item.is_veg ? "green" : "red" %>-500 rounded-xl" style="width:4px;height:4px;"></span>
          </div>
          <p class="text-<%= menu_item.is_veg ? "green" : "red" %>-600"><%= menu_item.is_veg ? "Veg" : "Non Veg" %></p>
        </div>
      </div>
    </div>
    <div class="flex justify-center items-center">
      <div class="pr-8 flex items-center justify-center">
      <%= link_to "-", "#{cart_path(cart_item.id)}?qty=#{cart_item.qty - 1}", method: "patch", class: "p-3 bg-green-100 border border-green-200" %>
        <div class="p-3 mx-1"><%= cart_item.qty %></div>
      <%= link_to "+", "#{cart_path(cart_item.id)}?qty=#{cart_item.qty + 1}", method: "patch", class: "p-3 bg-green-100 border border-green-200" %>
        
      </div>
      <div class="pr-8"><span class="text-green-800 text-lg">Rs.<%= menu_item.price * cart_item.qty %></span></div>

      <div class="pr-8">
        <%= link_to "#{cart_path(cart_item.id)}", method: :delete do %>
          <img src=<%= image_path("trash.svg") %>/>
        <% end %>
      </div>
      <div><i class="fa fa-close text-xs font-medium"></i></div>
    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="px-4 w-full max-w-screen-lg mx-auto my-16 pt-16 flex flex-wrap md:flex-nowrap">
<% if cart_items.length > 0 %>
  <div class="w-full overflow-hidden sm:w-full md:w-2/3 lg:w-2/3">
      <% cart_items.each do |cart_item| %>
        <div class="mb-4">
          <%= render partial: "cart_item_card", locals: { cart_item: cart_item, menu_item: MenuItem.find(cart_item.menu_item_id) } %>
        </div>
      <% end %>
    </div>
        
<div class="p-7 md:ml-4 w-full overflow-hidden sm:w-full md:w-1/3 lg:w-1/3 bg-green-50 rounded-2xl text-green-800 md:self-start">
  <h1 class="text-xl font-semibold mb-4 pb-4 border-b border-green-200">Price Details</h1>
  <div class="mb-4 border-b pb-4 text-base border-green-200">
    <div class="flex justify-between">
      <p>Sub Total</p>
      <p> <%= sprintf "%.2f", total %></p>
    </div>
    <div class="flex justify-between">
      <p>Tax <span>(inclusive)</span></p>
      <p><%= sprintf "%.2f", total * 0.12 %></p>
    </div>
    <div class="flex justify-between">
      <p>Delivery Charges</p>
      <p>+ 40.00</p>
    </div>
    <div class="flex justify-between">
      <p>Discount</p>
      <p>- 40.00</p>
    </div>
  </div>
  <div class="mb-4">
    <div class="flex justify-between text-lg">
      <p class="">Grand Total</p>
      <p><%= sprintf "%.2f", total %></p>
    </div>
  </div>
  <%= link_to "PLACE ORDER", orders_path, method: "post", class: "block px-4 pt-3 pb-4 border border-green-200 bg-green-500 text-center font-medium text-white hover:bg-green-400 transition-all rounded-lg" %>
  <% # <a href="/" class="block px-4 pt-3 pb-4 border border-green-200 bg-green-500 text-center font-medium text-white hover:bg-green-400 transition-all rounded-lg">PLACE ORDER</a> %>
</div>

    </div>
<% else %>
  <div class="w-full sm:w-full md:w-2/3 lg:w-2/3 text-center">
  <h1 class="text-2xl font-semibold text-green-700 text-center mb-12">Your Cart is Empty</h1>
  <a href="/" class="bg-green-200 px-6 py-3 rounded-lg mt-8">Show Menu</a>
</div>
<% end %>
    

</div>