config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/", to: "home#index"
  resources :menu_items
  resources :menus
  resources :users

  # auth
  get "/login" => "home#login", as: :login_path
  post "/login" => "users#login"

  delete "/logout" => "users#logout", as: :logout

  get "/signup" => "home#signup"
  post "/signup" => "users#create", as: :signup_path

  # cart
  get "/checkout" => "carts#index"
  resources :carts

  # order
  get "/orders/pending" => "orders#pending"
  resources :orders

  # dashboard
  get "/dashboard" => "home#dashboard"

  #sales
  get "/sales" => "sales#index"
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    from_date = params[:from_date] ? params[:from_date] : 1.month.ago
    to_date = params[:to_date] ? params[:to_date] : Time.now
    orders = Order.where("created_at BETWEEN '#{from_date}' AND '#{to_date}'").order("created_at")
    render "sales/index", :locals => { orders: orders }
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_sales_row.html.erb
<tr class="bg-white sm:hover:bg-green-50 flex sm:table-row flex-row sm:flex-row flex-wrap sm:flex-no-wrap mb-10 sm:mb-0">
  <td class="w-full sm:w-auto p-3 text-green-800 text-center border border-b block sm:table-cell relative sm:static underline">
        <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Order Id</span>
        <a href=<%= order_path(order.id) %>> #<%= order.id %></a>
  </td>
    <td class="w-full sm:w-auto p-3 text-green-800 text-center border border-b block sm:table-cell relative sm:static underline">
      <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Customer</span>
          <a href=<%= user_path(order.user_id) %>> #<%= order.user_id %> <%= order.user_name %></a>
    </td>
    <td class="w-full sm:w-auto p-3 text-green-800 text-center border border-b block sm:table-cell relative sm:static">
      <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Created At</span>
          <%= order.created_at %>
      </td>
      <td class="w-full sm:w-auto p-3 text-center border border-b block sm:table-cell relative sm:static text-green-900 bg-<%= order.delivered_at ? "green" : "yellow" %>-200">
        <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Status</span>
        <%= order.delivered_at ? "Delivered" : "Pending" %>
      </td>
      <td class="w-full sm:w-auto p-3 text-green-900 text-center border border-b block sm:table-cell relative sm:static">
        <span class="sm:hidden absolute top-0 left-0 bg-green-200 px-2 py-1 text-xs font-bold uppercase">Total Amount</span>
        ₹<%= order.total_price %>
   </td>
</tr>

app/views/sales/index.html.erb
<div class="max-w-screen-lg mx-auto min-h-screen pt-12" >
  <h1 class="text-3xl font-medium">Sales Report</h1>
  
  <%= form_with url: "/sales", class: "py-6 flex items-end", method: "get" do |form| %> 
  <div class="m-1">
  <%= form.label :from_date, "From", class: "block text-green-600" %>
  <%= form.date_field :from_date, class: "p-2 border-2 border-green-300 rounded-md text-green-800", required: true, value: params[:from_date] %>
  </div>
  <div class="m-1">
   <%= form.label :to_date, "To", class: "block text-green-600" %>
  <%= form.date_field :to_date, class: "p-2 border-2 border-green-300 rounded-md text-green-800", required: true, value: params[:to_date] %>
  </div>
  <div class="m-1">
    <input type="submit" name="date" id="date" class="bg-green-500 rounded-md text-white cursor-pointer font-semibold py-3 px-6 hover:bg-green-600" value="Show" />
  </div>
<% end %>

  <table class="border-collapse w-full mt-8">

  <thead>
    <tr>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Order Id</th>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Customer</th>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Created At</th>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Status</th>
      <th class="p-3 font-bold uppercase bg-green-200 text-green-900 border border-green-300 hidden sm:table-cell">Total Amount</th>
    </tr>
  </thead>
  <tbody>
  <% if orders.count > 0 %>
    <% orders.each do |order| %>
      <%= render partial: "sales_row", locals: { order: order } %>
    <% end %>
  <% else %>
  <tr class="bg-white sm:hover:bg-green-50 flex sm:table-row flex-row sm:flex-row flex-wrap sm:flex-no-wrap mb-10 sm:mb-0">
 <td colspan="5"  class="w-full sm:w-auto p-3 text-green-800 text-center border border-b block sm:table-cell relative sm:static">
        
    <h1 class="text-xl font-medium">No Pending Orders</h1>
  </td>
  </tr>
  <% end %>
  </tbody>
  </table>
</div>